@startuml
actor Client

participant CalendarController as CC
participant CalendarService    as CS

participant UserController     as UC
participant UserService        as US

== Calendar flows ==
Client -> CC: POST /api/v1/calendar/createCalendar\n(token, CreateCalendarRequest)
CC     -> CS: createCalendar(token, request)
CS     --> CC: CalendarResponse
CC     --> Client: 200 OK\nCalendarResponse

Client -> CC: PUT /api/v1/calendar/manageUsers\n(token, ManageUsersRequest)
CC     -> CS: manageUser(token, request)
CS     --> CC: CalendarResponse
CC     --> Client: 200 OK\nCalendarResponse

Client -> CC: PUT /api/v1/calendar/manageCalendar\n(token, ManageCalendarRequest)
CC     -> CS: manageCalendar(token, request)
CS     --> CC: CalendarResponse
CC     --> Client: 200 OK\nCalendarResponse

Client -> CC: POST /api/v1/calendar/createEvent\n(token, CreateEventRequest)
CC     -> CS: createEvent(token, request)
CS     --> CC: EventResponse
CC     --> Client: 200 OK\nEventResponse

Client -> CC: PUT /api/v1/calendar/manageEvent\n(token, ManageEventRequest)
CC     -> CS: manageEvent(token, request)
CS     --> CC: EventResponse
CC     --> Client: 200 OK\nEventResponse

Client -> CC: POST /api/v1/calendar/reactEvent\n(token, ReactEventRequest)
CC     -> CS: reactEvent(token, request)
CS     --> CC: ReactResponse
CC     --> Client: 200 OK\nReactResponse

== User flows ==
Client -> UC: POST /api/v1/user/register\n(SingUpRequest)
UC     -> US: registerUser(request)
US     --> UC: AuthResponse
UC     --> Client: 200 OK\nAuthResponse

Client -> UC: POST /api/v1/user/authorize\n(AuthorizeRequest)
UC     -> US: authorizeUser(request)
US     --> UC: AuthResponse
UC     --> Client: 200 OK\nAuthResponse

Client -> UC: PUT /api/v1/user/manage\n(token, ManageRequest)
UC     -> US: manageUser(token, request)
US     --> UC: ManageResponse
UC     --> Client: 200 OK\nManageResponse

Client -> UC: PUT /api/v1/user/logout\n(token)
UC     -> US: logout(token)
US     --> UC: LogoutResponse
UC     --> Client: 200 OK\nLogoutResponse

Client -> UC: PUT /api/v1/user/delete\n(token, password)
UC     -> US: deleteUser(token, password)
US     --> UC: DeleteResponse
UC     --> Client: 200 OK\nDeleteResponse

@enduml